language:
    - cpp

cache:
    apt: true

addons: 
    apt:
      sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      packages:
      - libboost1.55-all-dev

compiler:
    - gcc

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
